# **************************
#  Creation of the tag to trigger release
#  directelly on GitHub
#  with release-it (specific config)
# **************************

name: Tag Electron App on GitHub

on:
    workflow_dispatch:
        inputs:
            release_type:
                type: choice
                description: 'Update Major, Minor, Patch or RC (pre-release)'
                required: true
                options:
                    - -- --preRelease=rc
                    - -- patch
                    - -- minor
                    - -- major
                default: -- --preRelease=rc

jobs:
    release_it:
        runs-on: ubuntu-latest
        steps:
            - name: Github checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: git config
              run: |
                  git config user.name "${GITHUB_ACTOR}"
                  git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            - run: npm ci
            - run: npm run release:ci ${{ github.event.inputs.release_type }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
